services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/home/opam/bluesky-bot
    command: ["dune", "exec", "src/main.exe"]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
